/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/appointment_requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of AppointmentRequest resources.
         * @description Retrieves the collection of AppointmentRequest resources.
         */
        get: operations["api_appointment_requests_get_collection"];
        put?: never;
        /**
         * Creates a AppointmentRequest resource.
         * @description Creates a AppointmentRequest resource.
         */
        post: operations["api_appointment_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointment_requests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a AppointmentRequest resource.
         * @description Retrieves a AppointmentRequest resource.
         */
        get: operations["api_appointment_requests_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the AppointmentRequest resource.
         * @description Removes the AppointmentRequest resource.
         */
        delete: operations["api_appointment_requests_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the AppointmentRequest resource.
         * @description Updates the AppointmentRequest resource.
         */
        patch: operations["api_appointment_requests_id_patch"];
        trace?: never;
    };
    "/api/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Brand resources.
         * @description Retrieves the collection of Brand resources.
         */
        get: operations["api_brands_get_collection"];
        put?: never;
        /**
         * Creates a Brand resource.
         * @description Creates a Brand resource.
         */
        post: operations["api_brands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Brand resource.
         * @description Retrieves a Brand resource.
         */
        get: operations["api_brands_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Brand resource.
         * @description Removes the Brand resource.
         */
        delete: operations["api_brands_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Brand resource.
         * @description Updates the Brand resource.
         */
        patch: operations["api_brands_id_patch"];
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Company resources.
         * @description Retrieves the collection of Company resources.
         */
        get: operations["api_companies_get_collection"];
        put?: never;
        /**
         * Creates a Company resource.
         * @description Creates a Company resource.
         */
        post: operations["api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Company resource.
         * @description Retrieves a Company resource.
         */
        get: operations["api_companies_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Company resource.
         * @description Removes the Company resource.
         */
        delete: operations["api_companies_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Company resource.
         * @description Updates the Company resource.
         */
        patch: operations["api_companies_id_patch"];
        trace?: never;
    };
    "/api/api/equipment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Equipment resource.
         * @description Retrieves a Equipment resource.
         */
        get: operations["api_apiequipment_id_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Intervention resources.
         * @description Retrieves the collection of Intervention resources.
         */
        get: operations["api_interventions_get_collection"];
        put?: never;
        /**
         * Creates a Intervention resource.
         * @description Creates a Intervention resource.
         */
        post: operations["api_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interventions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Intervention resource.
         * @description Retrieves a Intervention resource.
         */
        get: operations["api_interventions_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Intervention resource.
         * @description Removes the Intervention resource.
         */
        delete: operations["api_interventions_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Intervention resource.
         * @description Updates the Intervention resource.
         */
        patch: operations["api_interventions_id_patch"];
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates a user token.
         * @description Creates a user token.
         */
        post: operations["login_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operating_systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of OperatingSystem resources.
         * @description Retrieves the collection of OperatingSystem resources.
         */
        get: operations["api_operating_systems_get_collection"];
        put?: never;
        /**
         * Creates a OperatingSystem resource.
         * @description Creates a OperatingSystem resource.
         */
        post: operations["api_operating_systems_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operating_systems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a OperatingSystem resource.
         * @description Retrieves a OperatingSystem resource.
         */
        get: operations["api_operating_systems_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the OperatingSystem resource.
         * @description Removes the OperatingSystem resource.
         */
        delete: operations["api_operating_systems_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the OperatingSystem resource.
         * @description Updates the OperatingSystem resource.
         */
        patch: operations["api_operating_systems_id_patch"];
        trace?: never;
    };
    "/api/statuses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Status resources.
         * @description Retrieves the collection of Status resources.
         */
        get: operations["api_statuses_get_collection"];
        put?: never;
        /**
         * Creates a Status resource.
         * @description Creates a Status resource.
         */
        post: operations["api_statuses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/statuses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Status resource.
         * @description Retrieves a Status resource.
         */
        get: operations["api_statuses_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Status resource.
         * @description Removes the Status resource.
         */
        delete: operations["api_statuses_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Status resource.
         * @description Updates the Status resource.
         */
        patch: operations["api_statuses_id_patch"];
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of Task resources.
         * @description Retrieves the collection of Task resources.
         */
        get: operations["api_tasks_get_collection"];
        put?: never;
        /**
         * Creates a Task resource.
         * @description Creates a Task resource.
         */
        post: operations["api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a Task resource.
         * @description Retrieves a Task resource.
         */
        get: operations["api_tasks_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the Task resource.
         * @description Removes the Task resource.
         */
        delete: operations["api_tasks_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the Task resource.
         * @description Updates the Task resource.
         */
        patch: operations["api_tasks_id_patch"];
        trace?: never;
    };
    "/api/task_interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of TaskIntervention resources.
         * @description Retrieves the collection of TaskIntervention resources.
         */
        get: operations["api_task_interventions_get_collection"];
        put?: never;
        /**
         * Creates a TaskIntervention resource.
         * @description Creates a TaskIntervention resource.
         */
        post: operations["api_task_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task_interventions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a TaskIntervention resource.
         * @description Retrieves a TaskIntervention resource.
         */
        get: operations["api_task_interventions_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the TaskIntervention resource.
         * @description Removes the TaskIntervention resource.
         */
        delete: operations["api_task_interventions_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the TaskIntervention resource.
         * @description Updates the TaskIntervention resource.
         */
        patch: operations["api_task_interventions_id_patch"];
        trace?: never;
    };
    "/api/type_equipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of TypeEquipment resources.
         * @description Retrieves the collection of TypeEquipment resources.
         */
        get: operations["api_type_equipments_get_collection"];
        put?: never;
        /**
         * Creates a TypeEquipment resource.
         * @description Creates a TypeEquipment resource.
         */
        post: operations["api_type_equipments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type_equipments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a TypeEquipment resource.
         * @description Retrieves a TypeEquipment resource.
         */
        get: operations["api_type_equipments_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the TypeEquipment resource.
         * @description Removes the TypeEquipment resource.
         */
        delete: operations["api_type_equipments_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the TypeEquipment resource.
         * @description Updates the TypeEquipment resource.
         */
        patch: operations["api_type_equipments_id_patch"];
        trace?: never;
    };
    "/api/type_interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of TypeIntervention resources.
         * @description Retrieves the collection of TypeIntervention resources.
         */
        get: operations["api_type_interventions_get_collection"];
        put?: never;
        /**
         * Creates a TypeIntervention resource.
         * @description Creates a TypeIntervention resource.
         */
        post: operations["api_type_interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type_interventions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a TypeIntervention resource.
         * @description Retrieves a TypeIntervention resource.
         */
        get: operations["api_type_interventions_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the TypeIntervention resource.
         * @description Removes the TypeIntervention resource.
         */
        delete: operations["api_type_interventions_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the TypeIntervention resource.
         * @description Updates the TypeIntervention resource.
         */
        patch: operations["api_type_interventions_id_patch"];
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves the collection of User resources.
         * @description Retrieves the collection of User resources.
         */
        get: operations["api_users_get_collection"];
        put?: never;
        /**
         * Creates a User resource.
         * @description Creates a User resource.
         */
        post: operations["api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieves a User resource.
         * @description Retrieves a User resource.
         */
        get: operations["api_users_id_get"];
        put?: never;
        post?: never;
        /**
         * Removes the User resource.
         * @description Removes the User resource.
         */
        delete: operations["api_users_id_delete"];
        options?: never;
        head?: never;
        /**
         * Updates the User resource.
         * @description Updates the User resource.
         */
        patch: operations["api_users_id_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppointmentRequest: {
            readonly id?: number;
            /** Format: date-time */
            date?: string | null;
            title?: string;
            description?: string | null;
            status?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            approved_by?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            company?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            equipment?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            typeIntervention?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            intervention?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            approvedBy?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Brand: {
            readonly id?: number;
            name?: string;
            equipment?: string[];
            logo?: string | null;
        };
        "Brand-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
        };
        Company: {
            readonly id?: number;
            name?: string;
            about?: string | null;
            type?: string | null;
            address?: string;
            city?: string;
            zip_code?: string;
            website?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            interventions?: string[];
            users?: string[];
            appointmentRequests?: string[];
            zipCode?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Equipment-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            type_equipment?: components["schemas"]["TypeEquipment-equipment.read_equipment.details"] | null;
            operating_system?: components["schemas"]["OperatingSystem-equipment.read_equipment.details"] | null;
            brand?: components["schemas"]["Brand-equipment.read_equipment.details"] | null;
            interventions?: components["schemas"]["Intervention-equipment.read_equipment.details"][];
            appointmentRequests?: string[];
        };
        Intervention: {
            readonly id?: number;
            title?: string;
            description?: string | null;
            message_report?: string | null;
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            typeIntervention?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            company?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            status?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            user?: string | null;
            taskInterventions?: string[];
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            appointmentRequest?: string | null;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            equipment?: string | null;
            messageReport?: string | null;
            /** Format: date-time */
            startDate?: string | null;
            /** Format: date-time */
            endDate?: string | null;
            readonly duration?: number | null;
            readonly durationInHours?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "Intervention-equipment.read_equipment.details": {
            readonly id?: number;
            title?: string;
            description?: string | null;
            message_report?: string | null;
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            typeIntervention?: components["schemas"]["TypeIntervention-equipment.read_equipment.details"];
            status?: components["schemas"]["Status-equipment.read_equipment.details"] | null;
        };
        OperatingSystem: {
            readonly id?: number;
            name?: string;
            equipment?: string[];
        };
        "OperatingSystem-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
        };
        Status: {
            readonly id?: number;
            name?: string;
        };
        "Status-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
        };
        Task: {
            readonly id?: number;
            name?: string;
            price?: number;
            description?: string;
            taskInterventions?: string[];
        };
        TaskIntervention: {
            readonly id?: number;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            task?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            intervention?: string;
        };
        TypeEquipment: {
            readonly id?: number;
            name?: string;
            equipment?: string[];
        };
        "TypeEquipment-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
        };
        TypeIntervention: {
            readonly id?: number;
            name?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            interventions?: string[];
            appointmentRequests?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        "TypeIntervention-equipment.read_equipment.details": {
            readonly id?: number;
            name?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        User: {
            readonly id?: number;
            email?: string;
            role: string;
            /** @description The hashed password */
            password?: string;
            first_name: string;
            last_name?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * Format: iri-reference
             * @example https://example.com/
             */
            company?: string | null;
            equipment?: string[];
            appointmentRequests?: string[];
            zipcode?: string | null;
            city?: string | null;
            phone?: string | null;
            address?: string | null;
            /** @description A visual identifier that represents this user. */
            readonly userIdentifier?: string;
            firstName?: string;
            lastName?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_appointment_requests_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AppointmentRequest collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRequest"][];
                };
            };
        };
    };
    api_appointment_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new AppointmentRequest resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentRequest"];
            };
        };
        responses: {
            /** @description AppointmentRequest resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRequest"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_appointment_requests_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AppointmentRequest identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AppointmentRequest resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRequest"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_appointment_requests_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AppointmentRequest identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AppointmentRequest resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_appointment_requests_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description AppointmentRequest identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated AppointmentRequest resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["AppointmentRequest"];
            };
        };
        responses: {
            /** @description AppointmentRequest resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRequest"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_brands_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"][];
                };
            };
        };
    };
    api_brands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Brand resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Brand"];
            };
        };
        responses: {
            /** @description Brand resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_brands_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Brand identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_brands_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Brand identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Brand resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_brands_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Brand identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Brand resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Brand"];
            };
        };
        responses: {
            /** @description Brand resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Brand"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_companies_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"][];
                };
            };
        };
    };
    api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Company resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Company"];
            };
        };
        responses: {
            /** @description Company resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_companies_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Company identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_companies_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Company identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Company resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_companies_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Company identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Company resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Company"];
            };
        };
        responses: {
            /** @description Company resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Company"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_apiequipment_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Equipment identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Equipment resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Equipment-equipment.read_equipment.details"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_interventions_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"][];
                };
            };
        };
    };
    api_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Intervention resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Intervention"];
            };
        };
        responses: {
            /** @description Intervention resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_interventions_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_interventions_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intervention resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_interventions_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Intervention identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Intervention resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Intervention"];
            };
        };
        responses: {
            /** @description Intervention resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Intervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The login data */
        requestBody: {
            content: {
                "application/json": {
                    email: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description User token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        readonly token: string;
                    };
                };
            };
        };
    };
    api_operating_systems_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OperatingSystem collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingSystem"][];
                };
            };
        };
    };
    api_operating_systems_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new OperatingSystem resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatingSystem"];
            };
        };
        responses: {
            /** @description OperatingSystem resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingSystem"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_operating_systems_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OperatingSystem identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OperatingSystem resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingSystem"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_operating_systems_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OperatingSystem identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OperatingSystem resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_operating_systems_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OperatingSystem identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated OperatingSystem resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["OperatingSystem"];
            };
        };
        responses: {
            /** @description OperatingSystem resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatingSystem"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_statuses_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"][];
                };
            };
        };
    };
    api_statuses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Status resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description Status resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_statuses_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Status identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_statuses_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Status identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_statuses_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Status identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Status resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Status"];
            };
        };
        responses: {
            /** @description Status resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tasks_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new Task resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
            };
        };
        responses: {
            /** @description Task resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tasks_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tasks_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_tasks_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated Task resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["Task"];
            };
        };
        responses: {
            /** @description Task resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_task_interventions_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TaskIntervention collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIntervention"][];
                };
            };
        };
    };
    api_task_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new TaskIntervention resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskIntervention"];
            };
        };
        responses: {
            /** @description TaskIntervention resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIntervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_task_interventions_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TaskIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TaskIntervention resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIntervention"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_task_interventions_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TaskIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TaskIntervention resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_task_interventions_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TaskIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated TaskIntervention resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TaskIntervention"];
            };
        };
        responses: {
            /** @description TaskIntervention resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskIntervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_equipments_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeEquipment collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEquipment"][];
                };
            };
        };
    };
    api_type_equipments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new TypeEquipment resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeEquipment"];
            };
        };
        responses: {
            /** @description TypeEquipment resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEquipment"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_equipments_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeEquipment identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeEquipment resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEquipment"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_equipments_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeEquipment identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeEquipment resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_equipments_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeEquipment identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated TypeEquipment resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TypeEquipment"];
            };
        };
        responses: {
            /** @description TypeEquipment resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeEquipment"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_interventions_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeIntervention collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeIntervention"][];
                };
            };
        };
    };
    api_type_interventions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new TypeIntervention resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["TypeIntervention"];
            };
        };
        responses: {
            /** @description TypeIntervention resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeIntervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_interventions_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeIntervention resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeIntervention"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_interventions_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TypeIntervention resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_type_interventions_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TypeIntervention identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated TypeIntervention resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["TypeIntervention"];
            };
        };
        responses: {
            /** @description TypeIntervention resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeIntervention"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_get_collection: {
        parameters: {
            query?: {
                /** @description The collection page number */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The new User resource */
        requestBody: {
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_id_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_id_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User resource deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_users_id_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User identifier */
                id: string;
            };
            cookie?: never;
        };
        /** @description The updated User resource */
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["User"];
            };
        };
        responses: {
            /** @description User resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
