services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mobile_cda}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
