name: PHP Lint

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  php-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
        
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: backend/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Install dependencies
      working-directory: ./backend
      run: composer install --prefer-dist --no-progress
      
    - name: Run PHP-CS-Fixer
      working-directory: ./backend
      run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
      
    - name: Run PHPStan
      working-directory: ./backend
      run: vendor/bin/phpstan analyse --error-format=github