name: Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  test:
    name: "${{ matrix.operating-system }} / PHP ${{ matrix.php-version }}"
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: false
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: proaxive_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      matrix:
        operating-system: ["ubuntu-latest"]
        php-version: ["8.3"]

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "intl, mbstring, pdo_pgsql, zip"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: "Add PHPUnit matcher"
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: "Install dependencies"
        run: composer install --ansi --no-interaction --no-progress --no-scripts

      - name: "Prepare test database"
        run: |
          mkdir -p var
          cp .env.test.ci .env.test.local
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --env=test --no-interaction
          php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: "Run tests"
        run: vendor/bin/phpunit
